project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: "How TO - MBOA Correlaties op teamniveau"
  author: "Corneel den Hartogh"
  page-navigation: true
  chapters:
    - index.qmd
    #- 00_project_setup.qmd
    - analysis/01_ingest.qmd
    - analysis/02_combine.qmd
    - analysis/03_correlate.qmd

# Custom chapter numbering
number-sections: true

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Laat code zien"

editor: source
execute:
  cache: true
  freeze: auto
  include: true
