
default:
  proj_name: "MBOA Analysis - Cefero"
  copyright_holder: "Cefero"
  proj_web_page: "www.cefero.nl"
  proj_email: "corneel@cefero.nl"

  data_raw_dir: "data/exports"
  data_ingested_dir: "data/ingested"
  data_prepared_dir: "data/prepared"
  #data_transformed_dir: "data/transformed"
  data_combined_dir: "data/combined"
  data_analysed_dir: "data/analysed"
  data_test_dir: "data/test"
  modelled_dir: "data/modelled"
  data_reference_dir: "data/reference"
  first_year: 2019
  last_year: 2023

  # Modeling settings
  model_settings:
    test_run: false  # Set to true for test runs with limited programs
    test_programs: ["Helpende Zorg en Welzijn (23181)", "Juridische administratief (23152)"]  # Programs to use for test runs
    test_levels: [2, 3]  # Education levels to use for test runs
    training_cohort_years: [2020, 2021, 2022]  # Years to use for training data
    test_cohort_year: 2023  # Year to use for test data
    min_training_samples: 40  # Minimum number of training samples required
    min_test_samples: 15  # Minimum number of test samples required
    min_minority_class: 5  # Minimum number of samples in minority class

  # The following settings are general settings that determine which data sources are use

  # Data grelated to enrollments (verbintenis / inschrijving)
  enrollments_basics:
    name: "enrollments_basics"
    filename: "Verbintenis zonder AVG vanaf 2018.csv"

  enrollments_level:
    name: "enrollments_level"
    filename: "VerbintenisNiveau.csv"

  enrollments_flex:
    name: "flex"
    filename: "IsFlex.csv"

  cohorts:
    name: "cohorts"
    filename: "Cohort zonder AVG.csv"

  reasons_for_leaving:
    name: "reasons_for_leaving"
    filename: "Reden uitschrijvingen.csv"

  study_advices:
    name: "study_advices"
    filename: "Studieadvies.csv"

  enrollments_application:
    name: "enrollments_application"
    filename: "s_edu_aanmelding (zonder AVG).csv"

  students_demographics:
    name: "students_demographics"
    filename: "Demografie.csv"

  enrollments_special_needs:
    name: "enrollments_special_needs"
    filename: "Passend onderwijs.csv"

  enrollments_ibp:
    name: "enrollments_ibp"
    filename: "Studenten met IBP.csv"

  bpv_registrations:
    name: "bpv_registrations"
    filename: "BPV Inschrijving.csv"

  bpv_statusses:
    name: "bpv_statusses"
    filename: "BPV Statusovergangen.csv"

  teams:
    name: "teams"
    filename: "Intern.OrganisatieEenheidMBOA.csv"

  locations:
    name: "locations"
    filename: "s_edu_locatie.csv"

  attendance_observations:
    name: "attendance_observations"
    filename: "Waarnemingen.csv"

  enrollment_to_sk_mapping:
    name: "enrollment_to_sk_mapping"
    filename: "Koppeltabel SK_Ins - Verbintenis.csv"

  crebo_to_organisation_mapping:
    name: "crebo_to_organisation_mapping"
    filename: "JOB Crebo Koppeltabel.csv"

  group_placements:
    name: "group_placements"
    filename: "Groepsinschrijving (dwh).csv"

# Data related to programmes (opleidingen)

  programmes_basics:
    name: "programmes_basics"
    filename: "s_edu_Opleiding (zonder AVG kolommen).csv"

  programme_bc_codes:
    name: "programme_bc_codes"
    filename: "Opleiding met bc-code.csv"

  exam_plans:
    name: "exam_plans"
    filename: "Examenplan.csv"

  # group_participation:
  #   name: "group_participation"
  #   filename: "Groepsdeelname.csv"

  employees_contract_basics_2023:
    name: "employees_contract_basics_2023"
    filename: "Medewerkers MBOA 2023-10-01.csv"

  employees_contract_basics_2022:
    name: "employees_contract_basics_2022"
    filename: "Medewerkers MBOA 2022-10-01.csv"

  employees_contract_basics_2021:
    name: "employees_contract_basics_2021"
    filename: "Medewerkers MBOA 2021-10-01.csv"

  employees_contract_basics_2020:
    name: "employees_contract_basics_2020"
    filename: "Medewerkers MBOA 2020-10-01.csv"

  employees_contract_basics_2019:
    name: "employees_contract_basics_2019"
    filename: "Medewerkers MBOA 2019-10-01.csv"

  employees_contract_extra_fte_2023:
    name: "employees_contract_extra_fte_2023"
    filename: "Aanvulling FTE uit Looncomponent 2023-10-01 .csv"

  employees_contract_extra_fte_2022:
    name: "employees_contract_extra_fte_2022"
    filename: "Aanvulling FTE uit Looncomponent 2022-10-01 .csv"

  employees_contract_extra_fte_2021:
    name: "employees_contract_extra_fte_2021"
    filename: "Aanvulling FTE uit Looncomponent 2021-10-01 .csv"

  employees_contract_extra_fte_2020:
    name: "employees_contract_extra_fte_2020"
    filename: "Aanvulling FTE uit Looncomponent 2020-10-01 .csv"

  employees_contract_extra_fte_2019:
    name: "employees_contract_extra_fte_2019"
    filename: "Aanvulling FTE uit Looncomponent 2019-10-01 .csv"

  employee_absences:
    name: "employee_absences"
    filename: "Verzuim medewerkers.csv"

  # students_prior_education:
  #   name: "students_prior_education"
  #   filename: "Vooropleiding studenten.csv"

  students_prior_education:
    name: "students_prior_education"
    filename: "Vooropleiding.csv"

  teams_results_retention_start:
    name: "teams_results_retention_start"
    filename: "startersresultaat_per_jaar_per_team.csv"

  teams_results_degree:
    name: "teams_results_degree"
    filename: "diplomaresultaat_per_jaar_per_team.csv"

  teams_results_year:
    name: "teams_results_year"
    filename: "jaarresultaat_per_jaar_per_team.csv"

  employees_job_type_2024:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2024-10-01.csv"

  employees_job_type_2023:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2023-10-01.csv"

  employees_job_type_2022:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2022-10-01.csv"

  employees_job_type_2021:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2021-10-01.csv"

  employees_job_type_2020:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2020-10-01.csv"

  employees_job_type_2019:
    name: "employees_job_type"
    filename: "Medewerker en Functie 2019-10-01.csv"

  students_satisfaction_2019:
    name: "students_satisfaction_2019"
    filename: "JOB 2020.csv"

  student_answers_satisfaction_2020:
    name: "student_answers_satisfaction_2020"
    filename: "JOB Light 2021 zonder Open vragen.csv"

  codebook_students_satisfaction_2020:
    name: "students_satisfaction_2020_codebook"
    filename: "JOB Light 2021 Codeboek.csv"

  students_satisfaction_2021:
    name: "students_satisfaction_2021"
    filename: "JOB 2022.csv"

  student_answers_satisfaction_2022:
    name: "student_answers_satisfaction_2022"
    filename: "JOB Light 2023.csv"

  codebook_students_satisfaction_2022:
    name: "codebook_students_satisfaction_2022"
    filename: "JOB Light 2023 Codeboek.csv"

  codebook_students_satisfaction_2023:
    name: "codebook_students_satisfaction_2023"
    filename: "JOB 2024 Codeboek.csv"

  codebook_students_satisfaction_mapping:
    name: "codebook_students_satisfaction_mapping"
    filename: "job_vragen_gedeeltelijke_mapping.csv"

  students_satisfaction_2023:
    name: "students_satisfaction_2023"
    filename: "JOB 2024.csv"

  employees_satisfaction_2020:
    name: "employees_satisfaction_2020"
    filename: "MTO 2020 zonder diensten.csv"

  employees_satisfaction_2022:
    name: "employees_satisfaction_2022"
    filename: "MTO 2022 zonder diensten.csv"

  employees_satisfaction_2024:
    name: "employees_satisfaction_2024"
    filename: "MTO 2024 zonder diensten.csv"

  codebook_employees_satisfaction_2020:
    name: "employees_satisfaction_2020_codebook"
    filename: "MTO 2020 Codeboek.csv"

  codebook_employees_satisfaction_2022:
    name: "employees_satisfaction_2022_codebook"
    filename: "MTO 2022 Codeboek.csv"

  codebook_employees_satisfaction_2024:
    name: "employees_satisfaction_2024_codebook"
    filename: "MTO 2024 Codeboek.csv"

  mapping_employees_satisfaction:
    name: "mapping_employees_satisfaction"
    filename: "KoppeltabelMWO_aanpassing.csv"

  codebook_employee_satisfaction_mapping:
    name: "codebook_employee_satisfaction_mapping"
    filename: "MTO_vragen_gedeeltelijke_mapping.csv"

  # Student postcode-related data files
  student_postcode_apcg:
    name: "student_postcode_apcg"
    filename: "DEELNEMER_postcode_APCG_CBS.csv"

  student_postcode_ses:
    name: "student_postcode_ses"
    filename: "DEELNEMER_postcode_ses_CBS.csv"


