---
title: "Correlaties"
---

{{< include 00_setup.qmd >}}

```{r}
#| include: false
#| freeze: false
#| cache: false

teams_file_path <- file.path(config::get("data_combined_dir"), "teams_combined_enriched.rds")

teams <- readRDS(teams_file_path)

```

We selecteren enkel kolommen die niet te vaak NA zijn en die meer dan 1 unieke waarde bevatten.

```{r}


teams_selected <- teams |>
    select_cols_for_correlation()

save_analysed(teams_selected)


```

We maken een correlatie dataframe en hernoemen de variabelen.

```{r}

teams_correlation <- teams_selected |>
    correlate_teams() |>
    set_user_friendly_names()

save_analysed(teams_correlation)

```


```{r}

teams_correlation_result <- teams_selected |>
  select(where(is.numeric)) |>
  correlate() |>
  select(term, TEAM_startersresultaat_1_jaars) |>
  filter(term != "TEAM_startersresultaat_1_jaars") |>
  filter(TEAM_startersresultaat_1_jaars <= -0.25 | TEAM_startersresultaat_1_jaars >= 0.25) |>
  # Arrange by correlation value from highest to lowest
  arrange(TEAM_startersresultaat_1_jaars) |>
    filter(term != "MEDEWERKER_verzuim_kort_opgevuld", 
           term != "VERBINTENIS_is_passend_onderwijs_gevuld_opgevuld") |>
  mutate(
    term = str_replace_all(term, "_", " "),  # Replace underscores with spaces
    term = factor(term, levels = term)       # Keep the ordering
  )


ggplot(teams_correlation_result, 
       aes(y = term)) +
  geom_segment(aes(
    x = 0,
    xend = TEAM_startersresultaat_1_jaars,
    yend = term,
    color = TEAM_startersresultaat_1_jaars
  ), 
  linewidth = 2) +
  # Fixed position for numbers on the right
  geom_text(aes(
    x = 0.5,  # Fixed x position for all numbers
    label = sprintf("%.2f", TEAM_startersresultaat_1_jaars)
  ), 
  hjust = 0,  # Align text to the left at the fixed position
  size = 3,
  color = "black") +
  scale_color_gradient2(
    low = "indianred2",
    mid = "white",
    high = "skyblue1",
    limits = c(-0.5, 0.5),
    midpoint = 0
  ) +
  scale_x_continuous(limits = c(-0.6, 0.6)) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
    ggtitle("Hoge correlatie met Startersresultaat 1 jaar")

```


```{r}

teams_correlation_all <- teams_selected |>
  select(where(is.numeric)) |>
  correlate() |>
  select(term, TEAM_startersresultaat_1_jaars) |>
  filter(term != "TEAM_startersresultaat_1_jaars") |>
  filter(TEAM_startersresultaat_1_jaars > -0.25 & TEAM_startersresultaat_1_jaars < 0.25,
         TEAM_startersresultaat_1_jaars < -0.15 | TEAM_startersresultaat_1_jaars > 0.15
         ) |>
  # Arrange by correlation value from highest to lowest
  arrange(TEAM_startersresultaat_1_jaars) |>
    filter(term != "MEDEWERKER_verzuim_kort", 
           term != "VERBINTENIS_is_passend_onderwijs_gevuld_opgevuld") |>
  mutate(
    term = str_replace_all(term, "_", " "),  # Replace underscores with spaces
    #term = str_remove(term, " opgevuld"),    # Remove "opgevuld"
    term = factor(term, levels = term)       # Keep the ordering
  )


ggplot(teams_correlation_all, 
       aes(y = term)) +
  geom_segment(aes(
    x = 0,
    xend = TEAM_startersresultaat_1_jaars,
    yend = term,
    color = TEAM_startersresultaat_1_jaars
  ), 
  linewidth = 2) +
  # Fixed position for numbers on the right
  geom_text(aes(
    x = 0.5,  # Fixed x position for all numbers
    label = sprintf("%.2f", TEAM_startersresultaat_1_jaars)
  ), 
  hjust = 0,  # Align text to the left at the fixed position
  size = 3,
  color = "black") +
  scale_color_gradient2(
    low = "indianred2",
    mid = "white",
    high = "skyblue1",
    limits = c(-0.5, 0.5),
    midpoint = 0
  ) +
  scale_x_continuous(limits = c(-0.6, 0.6)) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
    ggtitle("Middelhoge correlatie met Startersresultaat 1 jaar")

```



